# PARAM CONFIGURATION FILE:
# Please, use,
# >> rosbag info file.bag
# to find the correct topic names.
#
# EXECUTION:
# python3 extract_rosbag.py

# specify input and ouput files
#rosbag_path: "/media/arvc/INTENSO/DATASETS/OUTDOOR/2024-03-06-17-30-39.bag"
#output_path: "/media/arvc/INTENSO/DATASETS/OUTDOOR/2024-03-06-17-30-39"

rosbag_path: '/media/arvc/INTENSO/DATASETS/OUTDOOR/2024-03-12-16-48-19.bag'
output_path: '/media/arvc/INTENSO/DATASETS/OUTDOOR/2024-03-12-16-48-19'

# Specify the topic name or null to save the data
# ODOMETRY
topic_name_odometry: '/husky_velocity_controller/odom' #"/odometry/filtered"

# GPS
topic_name_gps: "/gnss/fix"
topic_name_gps_filtered: null # "/gps/filtered"
topic_name_odometry_gps: null # "/odometry/gps"

# LIDAR
topic_name_point_cloud: "/ouster/points" # /os1/pointCloud
save_point_cloud_as_pcd: True
save_point_cloud_as_csv: False

# IMU
topic_name_imu: "/imu/data"

# CAMERA
topic_name_camera: null # "/aravis_cam/aravis_cam/image_raw"

# GROUND TRUTH
topic_name_ground_truth: null # "/ground_truth/state"

# Save transforms if needed
topic_name_tf: null #"/tf"
topic_name_tf_static: null # "/tf_static"




